name: "build image"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag version'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'xiaoxuan6/free-vip-video'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EVENT_NAME=${{ github.event_name }}
          if [[ $EVENT_NAME != 'workflow_dispatch' ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          else
            VERSION=${{ github.event.inputs.tag }}
          fi
          echo "输出版本号：$VERSION"
          docker build -t ghcr.io/xiaoxuan6/free-vip-video/free_vip:latest .
          docker login ghcr.io -u ${{ github.actor }} -p $GITHUB_TOKEN
          docker push ghcr.io/xiaoxuan6/free-vip-video/free_vip:latest
          docker tag ghcr.io/xiaoxuan6/free-vip-video/free_vip:latest ghcr.io/xiaoxuan6/free-vip-video/free_vip:$VERSION
          docker push ghcr.io/xiaoxuan6/free-vip-video/free_vip:$VERSION
